FROM golang:1.20.7

RUN go install github.com/bufbuild/buf/cmd/buf@v1.25.0
RUN go install github.com/fullstorydev/grpcurl/cmd/grpcurl@v1.8.7
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.31.0
RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.3.0

WORKDIR /app
COPY . .
